# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20170221_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
